INSERT INTO public.posts (id, title, author, content, password, view_count, created_at, modified_at, is_deleted) 
VALUES 
(1, 'The Forgotten Garden', 'Kim Jiyeon', 'A small hidden garden sits between two apartment buildings, tended secretly by residents for decades. Plants from around the world thrive in this urban oasis, creating a community bond stronger than the concrete surrounding it.', 'garden42', 4, '2025-04-26 22:15:47.840443', NULL, false),
(2, 'Midnight Code', 'Park Minho', 'A small hidden garden sits between two apartment buildings, tended secretly by residents for decades', 'c0der983', 1, '2025-04-26 22:26:24.863019', NULL, false),
(3, 'Cafe Nostalgia', 'Lee Soomin', 'The scent of freshly ground coffee beans transports me back to my grandmother''s kitchen. Every Sunday morning, she would brew a pot while telling stories of her childhood in Madrid. Now I continue the tradition, keeping her memory alive with each cup.', 'coffee56', 1, '2025-04-26 22:29:39.520945', NULL, false),
(4, 'Digital Archaeology', 'Choi Junho', 'Recovering data from obsolete storage formats feels like excavating ancient ruins. Each corrupted file carefully restored reveals fragments of history thought lost forever. Even in technology, nothing truly disappears.', 'dig2find', 1, '2025-04-26 22:30:09.507334', NULL, false),
(5, 'Running Against Time', 'Kang Hayoo', 'The morning trail welcomes me with dew-covered grass and birdsong. My footsteps join the rhythm of nature awakening. Each stride pushes away yesterday''s stress, creating space for today''s possibilities.', 'run2025', 0, '2025-04-26 22:30:33.077843', NULL, false),
(6, 'Symphony of Stars', 'Shin Dohyu', 'The desert night revealed stars I''d never seen from the city. Looking up, I finally understood what the ancient astronomers felt—that deep connection to the cosmos, humbling yet profound. We are made of the same elements as those distant lights.', 'galaxy87', 0, '2025-04-26 22:30:50.521057', NULL, false),
(7, 'Forgotten Languages', 'Yoon Jiwoo', 'My grandfather was the last person in our village who spoke our native dialect fluently. I recorded him telling stories for years, preserving words that would otherwise vanish. Languages carry more than communication—they hold entire worldviews.', 'words394', 0, '2025-04-26 22:31:11.147399', NULL, false),
(8, 'Bicycle Philosophy', 'Bae Seojun', 'Life lessons come easiest on two wheels. Balance requires constant small adjustments. Forward momentum solves most problems. And sometimes, you need to coast downhill and enjoy the ride without overthinking.', 'pedal248', 1, '2025-04-26 22:31:29.192671', NULL, false),
(9, 'Urban Foraging', 'Jang Minji', 'The city hides edible treasures for those who know where to look. Mulberry trees line forgotten alleys, wild herbs grow through sidewalk cracks, and abandoned lots become unexpected orchards. Urban foraging connects us to our gatherer roots.', 'wild5432', 1, '2025-04-26 22:31:45.999336', NULL, false),
(10, 'Analog Revival', 'Han Jiseok', 'Digital convenience can''t replicate the ritual of vinyl records—selecting an album, carefully placing the needle, and committing to the full listening experience. Some technologies don''t improve with progress; they simply offer different values.', 'vinyl786', 1, '2025-04-26 22:32:07.515924', NULL, false);